SET NOCOUNT ON;SET XACT_ABORT ON;IF NOT EXISTS(SELECT 1 FROM lab.Evidence WHERE Stage='EXPLICIT_REFRESH' AND RowsTotal=120000 AND ModificationCounter=0 AND AsyncEnabled=1) THROW 51006,'FAIL_RESULT_CONTRACT: Aktualisierte Statistik fehlt.',1;
SELECT * FROM lab.Evidence ORDER BY CASE Stage WHEN 'BASELINE' THEN 1 WHEN 'OUT_OF_RANGE' THEN 2 ELSE 3 END;PRINT 'SQLPERF_SUMMARY|PASS|OK';
