/* OPT-003 / FWK-001 / FWK-008 / FWK-012 */
SET NOCOUNT ON;SET XACT_ABORT ON;
DECLARE @D varchar(7)='$(DemoId)',@R varchar(20)='$(RunToken)',@T sysname=N'$(TargetDatabase)',@M int=TRY_CONVERT(int,SERVERPROPERTY('ProductMajorVersion'));
IF @D<>'OPT-003' OR @T<>N'SQLPERF_LAB_OPT003_'+@R OR @R COLLATE Latin1_General_100_BIN2 LIKE '%[^A-Z0-9_]%' THROW 51000,'FAIL_CONTRACT: OPT-003-Zielkennung ist ungueltig.',1;
IF @M NOT BETWEEN 15 AND 17 BEGIN PRINT 'SQLPERF_SUMMARY|SKIP|SKIP_VERSION';RETURN;END;
IF HAS_PERMS_BY_NAME(NULL,NULL,'CREATE ANY DATABASE')<>1 AND HAS_PERMS_BY_NAME(N'master','DATABASE','CREATE DATABASE')<>1 BEGIN PRINT 'SQLPERF_SUMMARY|SKIP|SKIP_PERMISSION';RETURN;END;
SELECT @M MajorVersion,N'Sampling/Skew; keine globale Zustandsaenderung' Scope;
PRINT 'SQLPERF_SUMMARY|PASS|OK';
