SET NOCOUNT ON;SET XACT_ABORT ON;
DBCC SHOW_STATISTICS(N'lab.SkewData',N'IX_OPT003_Category') WITH STAT_HEADER,HISTOGRAM;
IF NOT EXISTS(SELECT 1 FROM lab.Evidence WHERE Stage='SAMPLE' AND RowsSampled<RowsTotal) BEGIN PRINT 'SQLPERF_SUMMARY|WARN|WARN_EMPIRICAL_VARIANCE';RETURN;END;
PRINT 'SQLPERF_SUMMARY|PASS|OK';
