SET NOCOUNT ON; SET XACT_ABORT OFF;
BEGIN TRY THROW 51010,'SYNTHETIC_DGN005_EVENT_A',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>51010 THROW; END CATCH;
BEGIN TRY THROW 51011,'SYNTHETIC_DGN005_EVENT_B',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>51011 THROW; END CATCH;
WAITFOR DELAY '00:00:02';
SELECT 1 Sequence,'DEMONSTRATION' Phase,'SUMMARY' CheckId,'PASS' Outcome,'OK' Code,N'2 synthetische Fehlerereignisse' ObservedValue,N'Fehlernummern >= 50000 in der markierten Datenbank' RequiredValue,N'Die Ereignisse wurden kontrolliert erzeugt.' Message; PRINT 'SQLPERF_SUMMARY|PASS|OK';
